package marloth.definition.enums

enum class MeshId {
  candle,
  billboard,
  cube,
  eyeball,
  grenadeLauncher,
  hogHead,
  key,
  line,
  missile,
  pants,
  personBody,
  pistol,
  prisonDoor,
  pumpkinHead,
  sentinelHead,
  shirt,
  shotgun,
  skySphere,
  sphere,
  spikyBall,
  treasureChest,
  wallLamp,

  // Architecture
  arcWall8thA,
  arcWall8thB,
  circleFloor,
  curvingStairStep,
  diagonalWall,
  fillerColumn,
  halfCircleFloor,
  halfLengthWall,
  halfSquareFloor,
  largeBrick,
  longPillowStep,
  longStairStep,
  longStep,
  quarterSlope,
  spiralStaircaseColumn,
  squareFloor,
  squareFloorHalfDiagonal,
  squareWallHalfHeight,
  squareWall,
  _squareWallPlain, // squareWall with different metadata
  squareWallDoorway,
  squareWallQuarterHeight,
  squareWallQuarterSlope,
  squareWallWindow
}
