package marloth.scenery.enums

object AccessoryId {
  const val candle = "candle"
  const val claws = "claws"
  const val damageBurning = "damageBurning"
  const val damageChilled = "damageChilled"
  const val damagePoisoned = "damagePoisoned"
  const val dash = "dash"
  const val dashing = "dashing"
  const val entangle = "entangle"
  const val entangled = "entangled"
  const val entangling = "entangling"
  const val entangleImmune = "entangledImmune"
  const val graveDigger = "graveDigger"
  const val grenadeLauncher = "grenadeLauncher"
  const val mobile = "mobile"
  const val mobility = "mobility"
  const val rocketLauncher = "rocketLauncher"
  const val spiritRocketLauncher = "spiritRocketLauncher"
  const val pistol = "pistol"
  const val resistanceCold = "resistanceCold"
  const val resistanceFire = "resistanceFire"
  const val resistancePoison = "resistancePoison"
  const val shotgun = "shotgun"
  const val victoryKey = "victoryKey"
}
