package scenery.enums

enum class MeshId {
  candle,
  //  childBody,
//  childBoyClothes,
//  childBoyHair,
//  childEyes,
//  childGown,
//  childLongHair,
  billboard,
  cube,
  eyeball,
  hogHead,
  line,
  pants,
  personBody,
  pistol,
  prisonDoor,
  pumpkinHead,
  shirt,
  skySphere,
  sphere,
  spikyBall,
  treasureChest,
  wallLamp,

  // Architecture
  circleFloor,
  curvingStairStep,
  diagonalWall,
  fillerColumn,
  halfCircleFloor,
  halfSquareFloor,
  largeBrick,
  longPillowStep,
  longStairStep,
  longStep,
  quarterSlope,
  squareFloor,
  squareFloorHalfDiagonal,
  squareWallHalfHeight,
  squareWall,
  squareWallDoorway,
  squareWallQuarterHeight,
  squareWallQuarterSlope,
  squareWallWindow
}
